DROP TABLE IF EXISTS appointments;
DROP TABLE IF EXISTS doctor_schedules;
DROP TABLE IF EXISTS patients;
DROP TABLE IF EXISTS doctor_profiles;
DROP TABLE IF EXISTS users;
DROP EXTENSION IF EXISTS pgcrypto;
